- id: test
  alias: Main trigger
  trigger:
  - minutes: /1
    platform: time
    seconds: 0
  condition:
  - condition: template
    value_template: '{{ now().strftime("%H:%M") == states.sensor.trigger_time.state
      }}'
  - condition: state
    entity_id: binary_sensor.run_today
    state: 'on'
  action:
  - data:
      entity_id: ' script.test_script'
    service: script.turn_on
- id: pump_auto_on
  alias: Turn on pump when one of the channels is turned on
  trigger:
  - entity_id:
    - binary_sensor.running_now
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: switch.pump
    service: switch.turn_on
- id: pump_auto_off
  alias: Turn off pump when one of the channels is turned on
  trigger:
  - entity_id:
    - binary_sensor.running_now
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: switch.pump
    service: switch.turn_off
