homeassistant:
    # Name of the location where Home Assistant is running
    name: Sprinkler automation system
    # Location required to calculate the time the sun rises and sets
    latitude: 49.006614
    longitude: 8.388594
    elevation: 116
    unit_system: metric
    time_zone: Europe/Athens
    # Customization file
    customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
    # Secrets are defined in the file secrets.yaml
    # api_password: !secret http_password
    # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
    # base_url: example.duckdns.org:8123

recorder:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
python_script:

# GPIO ports
switch:
  - platform: rpi_gpio
    invert_logic: true
    ports:
      9:  Channel 1
      11: Channel 2
      0:  Channel 3
      5:  Channel 4
      6:  Channel 5
      13: Channel 6
      19: Channel 7
      26: Pump

# Number Sliders
input_number:
    trigger_hour:
        name: Hours
        icon: mdi:timer
        min: 0
        max: 23
        step: 1
    trigger_minute:
        name: Minutes
        icon: mdi:timer
        min: 0
        max: 55
        step: 5
    duration1:
        name: Duration Channel 1
        icon: mdi:timer
        min: 1
        max: 59
        step: 1
    duration2:
        name: Duration Channel 2
        icon: mdi:timer
        min: 1
        max: 59
        step: 1
    duration3:
        name: Duration Channel 3
        icon: mdi:timer
        min: 1
        max: 59
        step: 1
    duration4:
        name: Duration Channel 4
        icon: mdi:timer
        min: 1
        max: 59
        step: 1
    duration5:
        name: Duration Channel 5
        icon: mdi:timer
        min: 1
        max: 59
        step: 1

# Boolean switches
input_boolean:
    monday:
        name: Monday
        icon: mdi:calendar
    tuesday:
        name: Tuesday
        icon: mdi:calendar
    wednesday:
        name: Wednesday
        icon: mdi:calendar
    thursday:
        name: Thursday
        icon: mdi:calendar
    friday:
        name: Friday
        icon: mdi:calendar
    saturday:
        name: Saturday
        icon: mdi:calendar
    sunday:
        name: Sunday
        icon: mdi:calendar
    channel_1:
        name: Enable channel 1
    channel_2:
        name: Enable channel 2
    channel_3:
        name: Enable channel 3
    channel_4:
        name: Enable channel 4
    channel_5:
        name: Enable channel 5
    channel_6:
        name: Enable channel 6
    channel_7:
        name: Enable channel 7

# Trigger time sensor
sensor:
    - platform: template
      sensors:
        trigger_time:
          friendly_name: 'Time'
          value_template: >-
            {{ "%0.02d:%0.02d" | 
            format(states("input_number.trigger_hour") | 
            int, states("input_number.trigger_minute") | 
            int) }}
        weekday_test:
          friendly_name: 'Day of week'
          value_template: >-
            {{ now().weekday() }}
    - platform: time_date
      display_options:
        - 'time'
binary_sensor:
    - platform: template
      sensors:
        run_today:
          value_template: >-
            {{ is_state('binary_sensor.test_monday', 'on')
            or is_state('binary_sensor.test_tuesday', 'on')
            or is_state('binary_sensor.test_wednesday', 'on')
            or is_state('binary_sensor.test_thursday', 'on')
            or is_state('binary_sensor.test_friday', 'on')
            or is_state('binary_sensor.test_saturday', 'on')
            or is_state('binary_sensor.test_sunday', 'on')}}
        running_now:
          value_template: >-
            {{ is_state('switch.channel_1', 'on')
            or is_state('switch.channel_2', 'on')
            or is_state('switch.channel_3', 'on')
            or is_state('switch.channel_4', 'on')
            or is_state('switch.channel_5', 'on')
            or is_state('switch.channel_6', 'on')
            or is_state('switch.channel_7', 'on')}}
        test_monday:
          value_template: >-
            {{ now().weekday() == 0 and
            is_state('input_boolean.monday', 'on')}}
        test_tuesday:
          value_template: >-
            {{ now().weekday() == 1 and
            is_state('input_boolean.tuesday', 'on')}}
        test_wednesday:
          value_template: >-
            {{ now().weekday() == 2 and
            is_state('input_boolean.wednesday', 'on')}}
        test_thursday:
          value_template: >-
            {{ now().weekday() == 3 and
            is_state('input_boolean.thursday', 'on')}}
        test_friday:
          value_template: >-
            {{ now().weekday() == 4 and
            is_state('input_boolean.friday', 'on')}}
        test_saturday:
          value_template: >-
            {{ now().weekday() == 5 and
            is_state('input_boolean.saturday', 'on')}}
        test_sunday:
          value_template: >-
            {{ now().weekday() == 6 and
            is_state('input_boolean.sunday', 'on')}}
